// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fpmyfayvogusbpxctcmb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZwbXlmYXl2b2d1c2JweGN0Y21iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMTg3ODgsImV4cCI6MjA2OTg5NDc4OH0.-yVxbqxCosIpcRbuSvN22I0J53BEjx5w6R51crtojG8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});